# vim: ft=yaml

# References:
# - https://shatteredsilicon.net/cut-costs-and-simplify-your-mongodb-install-using-zfs-compression/
# - https://source.wiredtiger.com/11.3.1/tune_page_size_and_comp.html

# NOTE: Disabling compression since we're running on a ZFS dataset
# NOTE: Ensure that allocation_size matches the dataset recordsize.

# I chose 32k somewhat arbitrarily; I wanted something larger than the default
# so that compression performs better and since over the years, chat messages
# will become very numerous. But 64k seemed "too big" when comparing the amount
# of data in the blog post I referenced.

storage:
  wiredTiger:
    collectionConfig:
      blockCompressor: none
      configString: allocation_size=32k,internal_page_max=32k,leaf_page_max=1m
    engineConfig:
      journalCompressor: none
