# vim: ft=yaml.ansible

- name: Copy SteamCMD server install script
  ansible.builtin.template:
    src: install-server.txt.j2
    dest: "{{ (server_user.home, steamcmd.install_script) | path_join }}"
    owner: "{{ server_user.name }}"
    mode: '0600'
  register: install_script
  tags: steam

- name: Install Dedicated Server
  become: true
  become_user: "{{ server_user.name }}"
  become_method: su
  ansible.builtin.command:
    # NOTE: steamcmd really wants an absolute path for whatever reason
    cmd: "/usr/bin/steamcmd +runscript {{ (server_user.home, steamcmd.install_script) | path_join }}"
    chdir: "{{ server_user.home }}"
  register: steamcmd_run
  changed_when: "'Update state (0x61)' in steamcmd_run.stdout"
  when: install_script.changed
  tags: steam

- name: Set up systemd units
  tags: systemd
  notify: systemd daemon reload
  block:
    - name: Copy game server service unit
      ansible.builtin.template:
        src: "{{ systemd.service_file }}.j2"
        dest: "/etc/systemd/system/{{ systemd.service_file | basename }}"
        mode: "0644"
        owner: root
        group: root

    - name: Copy systemd mount units
      ansible.builtin.template:
        src: "{{ item.src }}.j2"
        dest: "/etc/systemd/system/{{ item.name }}"
        mode: "0644"
        owner: root
        group: root
      loop: "{{ systemd.mount_units }}"
      when: systemd.mount_units is defined

    - name: Copy additional systemd units
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item | basename }}"
        mode: "0644"
        owner: root
        group: root
      loop: "{{ systemd.extra_units }}"
      when: systemd.extra_units is defined

    - name: Create directory for game server drop-in service files
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ systemd.service_file | basename }}.d"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Copy SteamCMD drop-in service file
      ansible.builtin.template:
        src: 20-steamcmd.conf.j2
        dest: "/etc/systemd/system/{{ systemd.service_file | basename }}.d/20-steamcmd.conf"
        mode: "0644"
        owner: root
        group: root

    # NOTE: systemd is a bit annoying and checks ExecStart directives for
    # non-existent executables. Since a service might refer to an executable
    # on one of the mounts, we'll eagerly start it so that verify won't fail.
    - name: Start systmed mount units
      ansible.builtin.systemd_service:
        name: "{{ item.name }}"
        state: started
        daemon_reload: true
      loop: "{{ systemd.mount_units }}"
      loop_control:
        label: "{{ item.name }}"
      when: (systemd.verify | default(True)) and systemd.mount_units is defined

    - name: Verify systemd units
      vars:
        units:
          - "{{ systemd.service_file }}"
          - "{{ systemd.extra_units | default(None) }}"
          - "{{ (systemd.mount_units is defined) | ternary(systemd.mount_units | map(attribute='name'), None) }}"
      ansible.builtin.command:
        cmd: systemd-analyze verify /etc/systemd/system/{{ item | basename }}
      loop: "{{ units | flatten }}"
      changed_when: false
      when: systemd.verify | default(True)

    - name: Enable game server service
      ansible.builtin.systemd_service:
        name: "{{ systemd.service_file | basename }}"
        enabled: true
