# vim: ft=yaml.ansible

- name: Add Tailscale repository
  vars:
    release: "{{ ansible_facts.distribution_release }}"
  ansible.builtin.deb822_repository:
    name: tailscale
    uris: https://pkgs.tailscale.com/stable/debian
    suites: "{{ release }}"
    components: main
    signed_by: "https://pkgs.tailscale.com/stable/debian/{{ release }}.noarmor.gpg"

- name: Update package index
  ansible.builtin.apt:
    update_cache: true
