rift.lan

[proxmox]
pve.lan
pbs.lan

[debserver]
audiobookshelf
kf1server.lan
zomboid.lan
pihole.lan
pihole2.lan
pkgcache.lan
smtp-relay.lan
forgejo.lan
pve.lan
pbs.lan

[pihole]
pihole.lan
pihole3.lan

[gameserver]
kf1server.lan
zomboid.lan
