# vim: ft=yaml.ansible

- name: Killing Floor 1 Dedicated Server with FastDL
  hosts: kf1server.lan
  remote_user: root
  vars_files:
    - kf1server/settings.yml
  vars:
    game:
      name: Killing Floor
      app_id: 215360
      install_dir: "{{ (server_user.home, 'base') | path_join }}"
      config_dir: "{{ (server_user.home, '.killingfloor') | path_join }}"
      config_file: "{{ (game.config_dir, 'System/KillingFloor.ini') | path_join }}"
      workshop_dir: "{{ (server_user.home, '.local/share/Steam/steamapps/workshop/content/1250') | path_join }}"
    overlay:
      target: "{{ (server_user.home, 'kf1server') | path_join }}"
      mount_unit: "{{ overlay.target[1:] | replace('/', '-') }}.mount"
      upper: "{{ (server_user.home, 'varlayer') | path_join }}"
      lower:
        - "{{ (server_user.home, 'custom') | path_join }}"
        - "{{ game.install_dir | replace(' ', '\\ ') }}"
      work_dir: "{{ (server_user.home, '.work') | path_join }}"
    nginx:
      server_name:
        - kf1.zeronet.dimensionzero.net
        - kf1server.lan
    systemd:
      unit_prefix: kf1server
      service_file: "{{ ('kf1server', systemd.unit_prefix) | path_join }}.service"
      mount_units:
        - src: "{{ ('kf1server', systemd.unit_prefix) | path_join }}.mount"
          name: "{{ overlay.mount_unit }}"
    steamcmd:
      user: dimensionzeronet
      password: !vault |
        $ANSIBLE_VAULT;1.2;AES256;kf1server
        35613566333164653739393862623464386564353062613761653934306163363033636438653638
        3032656533326439356365393435663261316665376630360a336136646230373963326365646262
        65306566323064313733333235633864623735343837343639633562656264333333353666616337
        6266393064663832370a623734333837303839393065656638633064306634343165323939326138
        31353338383538343634663532323831323964366635623630393438616534656432
      install_script: install-server.txt
    steamcmd_debian_repo_url: http://pkgcache.lan/debian
    steamcmd_debsec_repo_url: http://pkgcache.lan/debsec
  roles:
    - steamcmd
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      tags:
        - install
        - nginx

    - name: Create symlink to workshop directory
      ansible.builtin.file:
        src: "{{ game.workshop_dir }}"
        dest: "{{ (server_user.home, 'workshop') | path_join }}"
        state: link
        owner: "{{ server_user.name }}"
        group: "{{ server_user.name }}"
        force: true

    - name: Create directories for overlayfs
      ansible.builtin.file:
        path: "{{ (server_user.home, item) | path_join }}"
        state: directory
        mode: '0755'
        owner: "{{ server_user.name }}"
        group: "{{ server_user.name }}"
      loop:
        - .work
        - custom
        - kf1server
        - varlayer
      tags: overlay

    - name: Link ucc.log to /dev/null
      ansible.builtin.file:
        src: /dev/null
        dest: "{{ (game.config_dir, 'System/ucc.log') | path_join }}"
        state: link
        force: true
      tags: config

    - name: Check for KillingFloor.ini
      ansible.builtin.stat:
        path: "{{ game.config_file }}"
      register: stat_kf1config
      tags: config

    - name: Create base KillingFloor.ini from Default.ini
      ansible.builtin.copy:
        src: "{{ (game.install_dir, 'System/Default.ini') | path_join }}"
        dest: "{{ game.config_file }}"
        remote_src: true
        mode: preserve
      when: not stat_kf1config.stat.exists
      tags: config

    - name: Configure kf1server settings
      module_defaults:
        community.general.ini_file:
          path: "{{ game.config_file }}"
          mode: '0644'
          owner: steam
          group: steam
          create: false
          no_extra_spaces: true
      tags: config
      block:
        - name: Set server name
          community.general.ini_file:
            section: Engine.GameReplicationInfo
            option: ServerName
            value: "{{ server_settings.server_name }}"

        - name: Set server MOTD
          community.general.ini_file:
            section: Engine.GameReplicationInfo
            option: MessageOfTheDay
            value: "{{ server_settings.motd }}"

        - name: Set server admin name
          community.general.ini_file:
            section: Engine.GameReplicationInfo
            option: AdminName
            value: "{{ server_settings.admin_name }}"

        - name: Set server admin password
          community.general.ini_file:
            section: Engine.AccessControl
            option: AdminPassword
            value: "{{ server_settings.admin_password }}"

        - name: Set server game password
          community.general.ini_file:
            section: Engine.AccessControl
            option: GamePassword
            value: "{{ server_settings.game_password }}"

        - name: Set Map Voting Handler
          community.general.ini_file:
            section: Engine.GameInfo
            option: VotingHandlerType
            value: KFMapVoteV2.KFVotingHandler

        # NOTE: Reference for client/server bandwidth and tick rates:
        # https://steamcommunity.com/sharedfiles/filedetails/?id=925630057

        - name: Set server tick rate
          community.general.ini_file:
            section: IpDrv.TcpNetDriver
            option: "{{ item }}"
            value: "{{ server_settings.tick_rate }}"
          loop:
            - NetServerMaxTickRate
            - LanServerMaxTickRate

        - name: Set max client rate
          community.general.ini_file:
            section: IpDrv.TcpNetDriver
            option: "{{ item }}"
            value: "{{ 88 * server_settings.tick_rate * server_settings.max_players }}"
          loop:
            - MaxClientRate
            - MaxInternetClientRate

        - name: Set max players
          community.general.ini_file:
            section: Engine.GameInfo
            option: MaxPlayers
            value: "{{ server_settings.max_players }}"

        - name: Set max spectators
          community.general.ini_file:
            section: Engine.GameInfo
            option: MaxSpectators
            value: "{{ server_settings.max_spectators }}"

        - name: Set HTTP download server URL
          community.general.ini_file:
            section: IpDrv.HTTPDownload
            option: RedirectToURL
            value: "http://{{ nginx.server_name[0] }}:80/"

        - name: Do not use UZ2 compression
          community.general.ini_file:
            section: IpDrv.HTTPDownload
            option: UseCompression
            value: false

        - name: Disable GameSpy uplink
          community.general.ini_file:
            section: IpDrv.MasterServerUplink
            option: UplinkToGamespy
            value: false

        - name: Remove log cmdline option
          community.general.ini_file:
            section: Editor.EditorEngine
            option: GameCommandLine
            value: ""

        - name: Set WebAdmin state
          community.general.ini_file:
            section: UWeb.WebServer
            option: bEnabled
            value: "{{ webadmin.enabled }}"

        - name: Set WebAdmin port
          community.general.ini_file:
            section: UWeb.WebServer
            option: ListenPort
            value: "{{ webadmin.port }}"

        - name: Allow admin game pausing
          community.general.ini_file:
            section: Engine.GameInfo
            option: bAdminCanPause
            value: true

    - name: Copy KFMapVoteV2 config
      ansible.builtin.template:
        src: kf1server/KFMapVote.ini.j2
        dest: "{{ (game.config_dir, 'System/KFMapVote.ini') | path_join }}"
        mode: '0644'
        owner: steam
        group: steam
      tags: config

    - name: Copy kf1server site config to sites-available
      ansible.builtin.template:
        src: "kf1server/kf1server.conf.j2"
        dest: "/etc/nginx/sites-available/kf1server.conf"
        owner: root
        group: root
        mode: '0644'
      register: nginx_cfg
      tags: nginx

    - name: Enable kf1server site config
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/kf1server.conf"
        dest: "/etc/nginx/sites-enabled/kf1server.conf"
        state: link
      tags: nginx

    - name: Disable default nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags: nginx

    # NOTE: This is done separately because the config is only a fragment and
    # needs the full context of /etc/nginx.conf where it is included from
    - name: Validate nginx config
      ansible.builtin.command:
        cmd: nginx -t -c /etc/nginx/nginx.conf
      changed_when: false
      when: nginx_cfg.changed
      tags: nginx

    - name: Enable and start nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: "{{ 'restarted' if (nginx_cfg.changed | default(False)) else 'started' }}"
        enabled: true
      tags:
        - nginx
        - systemd
