# vim: ft=yaml.ansible

# References:
# - https://www.apalrd.net/posts/2024/cluster_debcache/
# - https://www.youtube.com/watch?v=ydfsjWDPDyU
# - https://blog.nginx.org/blog/nginx-caching-guide
# - https://blog.nginx.org/blog/smart-efficient-byte-range-caching-nginx

- name: Set up package cache host
  hosts: pkgcache.lan
  remote_user: root
  vars:
    cache:
      path: /var/cache/pkgcache
      zone:
        name: generic
        size: 256m
      lifetime: 365d
      max_size: 100g
      min_free: 3g
      chunk_size: 1m
    log_path:
      access: /var/log/nginx/access.log
      error: /var/log/nginx/error.log
    site_filename: pkgcache.conf
  tasks:
    - name: Package cache exists
      ansible.builtin.file:
        path: "{{ cache.path }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0775"

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Disable default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy pkgcache site config to sites-available
      ansible.builtin.template:
        src: "pkgcache/{{ site_filename }}.j2"
        dest: "/etc/nginx/sites-available/{{ site_filename }}"
        owner: root
        group: root
        mode: '0644'
      register: copy_cfg

    - name: Enable pkgcache site config
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ site_filename }}"
        dest: "/etc/nginx/sites-enabled/{{ site_filename }}"
        state: link

    # NOTE: This is done separately because the config is only a fragment and
    # needs the full context of /etc/nginx.conf where it is included from
    - name: Validate nginx config
      ansible.builtin.command:
        cmd: nginx -t -c /etc/nginx/nginx.conf
      changed_when: false
      when: copy_cfg.changed

    - name: Enable and start nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: "{{ 'restarted' if copy_cfg.changed else 'started' }}"
        enabled: true


- name: Configure Debian servers to use pkgcache
  hosts: debserver
  remote_user: root
  ignore_unreachable: true
  tasks:
    - name: Check for /etc/apt/sources.list
      ansible.builtin.stat:
        path: /etc/apt/sources.list
      register: stat_sources

    - name: Back up legacy /etc/apt/sources.list
      ansible.builtin.command:
        cmd: mv /etc/apt/sources.list /etc/apt/sources.list~
        removes: /etc/apt/sources.list
        creates: /etc/apt/sources.list~
      when: stat_sources.stat.exists

    - name: Point Debian sources at pkgcache host
      ansible.builtin.template:
        src: pkgcache/debian.sources.j2
        dest: /etc/apt/sources.list.d/debian.sources
        owner: root
        group: root
        mode: "0644"
        backup: true
      register: debian_sources

    - name: Find obsolete pkgcache-* sources
      ansible.builtin.find:
        path: /etc/apt/sources.list.d
        patterns: pkgcache-*.sources
        file_type: file
      register: obsolete_pkgcache_sources

    - name: Remove obsolete pkgcache-* sources
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ obsolete_pkgcache_sources.files }}"
      loop_control:
        label: "{{ item.path | basename }}"

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true
        upgrade: false
      when: debian_sources.changed


- name: Configure Proxmox repositories to use pkgcache
  hosts: proxmox
  remote_user: root
  tasks:
    - name: Stat /etc/pve
      ansible.builtin.stat:
        path: /etc/pve
      register: stat_pve

    - name: Assert that host is running Proxmox Virtual Environment
      ansible.builtin.assert:
        that:
          - stat_pve.stat.exists
          - stat_pve.stat.isdir
        fail_msg: Host doesn't seem to be running Proxmox Virtual Environment

    # TODO: Refactor to use a template once we upgrade pve.lan
    - name: Add proxied Proxmox non-enterprise source
      ansible.builtin.deb822_repository:
        name: pve-non-enterprise
        types: deb
        uris: http://{{ pkgcache_hostname }}/proxmox
        suites: "{{ ansible_facts.distribution_release }}"
        components: pve-no-subscription
        signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
      register: proxmox_non_enterprise_sources
      tags: never

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true
        upgrade: false
      when: proxmox_non_enterprise_sources.changed
