# vim: ft=systemd

# Reference: https://creativeprojects.github.io/resticprofile/installation/docker/index.html

[Container]
Image=ghcr.io/creativeprojects/resticprofile

# Ensure a consistent hostname for backup metadata
HostName=shipyard

Volume=./profiles:/resticprofile:Z
Volume=%h/restic:/repo:z
Volume=%C/restic:/root/.cache/restic:Z
