server_user:
  name: steam
  home: /srv/steam

steamcmd:
  user: anonymous
  password: "{{ undef() }}"
  install_script: install-server.txt

systemd:
  verify: true

# Allow specifying a mirror/proxy for the Debian repos
steamcmd_debian_repo_url: http://deb.debian.org/debian
steamcmd_debsec_repo_url: http://security.debian.org
